server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;

    location = /ru { try_files /index.html =404; }
    location = /ua { try_files /index_ua.html =404; }
    location = /en { try_files /index_en.html =404; }
    location = /de { try_files /index_de.html =404; }
    location = /es { try_files /index_es.html =404; }

    location = /admin {
        auth_basic "Admin";
        auth_basic_user_file /usr/share/nginx/html/.htpasswd;
        try_files /admin.html =404;
    }

    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }
}
